theme: jekyll-theme-cayman
title: "CRASH: Raw Audio Score-based Generative Modeling for Controllable High-resolution Drum Sound Synthesis"
description: "Simon Rouard - Gaëtan Hadjeres"
github: [metadata]

markdown: kramdown
kramdown:
    math_engine: katex

plugins:
    - jemoji
